### ISSUE TITLE
Could you biuld binaries for actual QtCreator 4.0.2?

### ISSUE THREAD

**Issue by kolayuk** [OneMoreGres/qtc-paneencode#2]
Unfortunatelly lastest binaries are for Qt Creator 4.0.0, but actual version provided in Qt SDK 5.7 is 4.0.2, could you build & update binaries please? I have no Qt Creator sources to do it myself

**Comment by OneMoreGres** [comment]
API has been changed, so i had to "adjust" qtc's sources to make plugin working again. Although it shouldn't break binary compatibility, but pls make some tests before i commit it.

[Try here](http://rgho.st/private/8sYd7QGtj/76be4bd2cda11192c634d84c1ba7ca71)

> md5sum QtcPaneEncode-4.0.2-win.zip 
> 1668f7ba53ea17515add8936998050a3  QtcPaneEncode-4.0.2-win.zip

**Comment by OneMoreGres** [comment]
Suppose it works.
