### ISSUE TITLE
Didn't detect the text which needed to be converted

### ISSUE THREAD

**Issue by IS-Kuan** [OneMoreGres/qtc-paneencode#3]
Problem remains after installing qtc-paneencode:
<img width="763" alt="2016-11-14 15 54 55" src="https://cloud.githubusercontent.com/assets/20762725/20257241/32942666-aa83-11e6-8441-fb453cc57856.png">

Under Windows 7 + Traditional Chinese evnironment.

If any UI exist to select encoding manually? Thanks.

**Comment by OneMoreGres** [comment]
You can manually select encoding from settings page. It just set to `auto` by default.
Is that what you need?

**Comment by OneMoreGres** [comment]
I suppose this means "yes".
